services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # DB_SQLITE_FILE: "/data/database.sqlite" 
      DB_POSTGRES_HOST: 'nginx-pg'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'npmpass'
      DB_POSTGRES_NAME: 'npm'
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-pg
    networks:
      - nginx_network
    restart: unless-stopped

  nginx-pg:
    container_name: nginx-pg
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: 'npmpass'
      POSTGRES_DB: 'npm'
    volumes:
      - ./db/nginx-pg:/var/lib/postgresql/data
    networks:
      - nginx_network
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./db/portainer-data:/data
    ports:
      - 9000:9000
    networks:
      - nginx_network
    restart: unless-stopped

networks:
  nginx_network:
    name: nginx_network
    external: true